FROM osrf/ros:noetic-desktop-full

RUN apt-get update
RUN apt-get install -y git && apt-get install -y python3-pip && apt-get install -y curl
RUN curl -sSL http://get.gazebosim.org | sh
RUN mkdir -p ~/catkin_ws/src && \
    cd ~/catkin_ws/src/

RUN git clone https://github.com/NatnaelKebede-nerd/gazebo_mobile_robot_simulation.git && \
    cd ~/catkin_ws

RUN echo "ALL Done"
